import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useState, useLayoutEffect, useEffect } from 'react';
import styled, { css } from 'styled-components';
import ReactFullpage, { Item } from '@fullpage/react-fullpage';
import { activeSectionAtom } from '../store';
import { useAtom } from 'jotai';
import ScrollLine from '../components/ScrollLine';
import { motion } from 'framer-motion';

const Home: NextPage = () => {
  const [isFirstSectionLoaded, setIsFirstSectionLoaded] = useState(false);
  const [isSecondSectionLoaded, setIsSecondSectionLoaded] = useState(false);
  const [isThirdSectionLoaded, setIsThirdSectionLoaded] = useState(false);
  const [nextActiveSection, setNextActiveSection] = useAtom(activeSectionAtom);

  const onSectionLeave = (
    origin: Item,
    destination: Item,
    direction: string
  ) => {
    setNextActiveSection(destination.index);
  };

  const onSectionEnter = (
    origin: Item,
    destination: Item,
    direction: string
  ) => {
    if (destination.index === 0) {
      setIsFirstSectionLoaded(true);
    } else if (destination.index === 1) {
      setIsSecondSectionLoaded(true);
    } else if (destination.index === 2) {
      setIsThirdSectionLoaded(true);
    }
  };
  let easing = [0.175, 0.85, 0.42, 0.96];
  const imageVariants = {
    exit: { scale: 1, transition: { duration: 0.5, ease: easing } },
    enter: {
      scale: 2,
      transition: {
        duration: 0.5,
        ease: easing,
        delay: 1,
      },
    },
  };
  return (
    <MainContent
      variants={imageVariants}
      initial='exit'
      animate='enter'
      exit='exit'
    >
      <Head>
        <title>Hoang Tran</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ReactFullpage
        anchors={['1', '2', '3']}
        licenseKey={'YOUR_KEY_HERE'}
        scrollingSpeed={800}
        verticalCentered={false}
        css3={true}
        easingcss3={'cubic-bezier(.82,.28,.34,.62)'}
        onLeave={onSectionLeave}
        afterLoad={onSectionEnter}
        animateAnchor={true}
        credits={{
          enabled: false,
          label: 'Made with fullPage.js',
          position: 'right',
        }}
        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <IntroSection className={'section'}>
                <IntroductionWrapper fadeInDone={isFirstSectionLoaded}>
                  <GreetingParagraph>hi there,</GreetingParagraph>
                  <IntroParagraph>
                    my name is Hoang, I am an aspiring frontend developer and UX
                    designer based in Prague.
                  </IntroParagraph>
                </IntroductionWrapper>
              </IntroSection>
              <AboutSection className={'section'}>
                <SectionMainWrapper fadeInDone={isSecondSectionLoaded}>
                  <SecondSectionLabel>About me</SecondSectionLabel>
                  <DescriptionParagraph>
                    I'm a CTU graduate specializing in Human computer
                    interaction and someone who has always been passionate about
                    visually pleasing aesthetics. As a designer, I aim to create
                    interfaces with usability and users' needs in mind. As a
                    developer I create interactive experience using technologies
                    such as React, Typescript.
                  </DescriptionParagraph>
                </SectionMainWrapper>
              </AboutSection>
              <WorkSection className={'section'}>
                <SectionMainWrapper fadeInDone={isThirdSectionLoaded}>
                  <ThirdSectionLabel>Selected work</ThirdSectionLabel>
                  <SelectedWorkWrapper>
                    <ProjectLink href='/project/visualclass'>
                      visualclass,
                    </ProjectLink>
                    <ProjectLink href='/project/hub'>hub,</ProjectLink>
                    <ProjectLink href='/project/felsight'>
                      felsight,
                    </ProjectLink>
                    <ProjectLink href='/project/visuflights'>
                      visuflights,
                    </ProjectLink>
                    <ProjectLink href='/project/mintodo'>min todo,</ProjectLink>
                    <ProjectLink href='/project/hoang'>hoang tran,</ProjectLink>
                  </SelectedWorkWrapper>
                </SectionMainWrapper>
              </WorkSection>
            </ReactFullpage.Wrapper>
          );
        }}
      />
      <ScrollLine />
    </MainContent>
  );
};
const fadeInCss = css<{ fadeInDone: boolean }>`
  transition: opacity 500ms var(--easing), transform 900ms var(--easing);
  transform: ${(props) =>
    props.fadeInDone ? 'translateY(0px)' : 'translateY(-4rem)'};
  opacity: ${(props) => (props.fadeInDone ? '1' : '0')};
`;

const GreetingParagraph = styled.p`
  font-size: 4.5rem;
  margin-bottom: 4.8rem;
  margin-top: 0;
`;

const IntroParagraph = styled.p`
  font-size: 6.5rem;
  line-height: 9rem;
  max-width: 98rem;
  margin: 0;
`;

export const IntroSection = styled.section`
  height: 100vh;
  background-color: var(--primaryBeige);
  background-clip: content-box;
`;

const WorkSection = styled(IntroSection)`
  color: var(--primaryBlue);
`;

const AboutSection = styled(IntroSection)`
  background-color: var(--primaryBlue);
`;

const SecondSectionLabel = styled.h3`
  font-size: 2.4rem;
  color: var(--primaryBeige);
  margin-bottom: 4rem;
  margin-top: 0;
  font-weight: 400;
`;

const ThirdSectionLabel = styled(SecondSectionLabel)`
  color: var(--primaryBlue);
`;

const DescriptionParagraph = styled.p`
  font-size: 4.5rem;
  color: var(--primaryBeige);
  line-height: 9rem;
  padding: 0;
  margin: 0;
`;

const SelectedWorkWrapper = styled(DescriptionParagraph)`
  color: var(--primaryBlue);
  font-size: 6.5rem;
  display: flex;
  flex-wrap: wrap;
`;

const SectionMainWrapper = styled(motion.div)<{ fadeInDone: boolean }>`
  display: flex;
  flex-direction: column;
  margin-left: 26.4rem;
  padding-top: 22.4rem;
  max-width: 1300px;

  ${SecondSectionLabel} {
    ${fadeInCss}
  }
  ${DescriptionParagraph} {
    ${fadeInCss}
    transition-delay: 500ms;
  }
`;

const IntroductionWrapper = styled.div<{ fadeInDone: boolean }>`
  display: flex;
  flex-direction: column;
  color: var(--primaryBlue);
  margin-left: 26.4rem;
  padding-top: 26.4rem;

  ${GreetingParagraph} {
    ${fadeInCss}
  }
  ${IntroParagraph} {
    ${fadeInCss}
    transition-delay: 500ms;
  }
`;

export const ProjectLink = styled.a`
  text-decoration: none;
  color: var(--primaryBlue);
  margin-right: 2rem;
  &:after {
    content: '';
    display: block;
    width: 20%;
    height: 2px;
    border-radius: 8px;
    transition: width 0.7s var(--easing);
    background-color: var(--primaryBlue);
    margin-left: 2%;
  }
  &:hover::after {
    width: 80%;
  }

  &:visited {
    color: inherit;
  }
`;

const MainContent = styled(motion.div)``;

export default Home;
